### PR TITLE
Feature - Add Prettier to format the source files for consistency

### PR DESCRIPTION
**Pull request by pratikborsadiya**
Format the source files for consistency. This pull request initialises npm's package.json file and add Prettier as code formatting tool.

This is a first step towards adding a full fledged build system based on npm. Once this pull request is merged I will work on adding webpack as build tool to build JavaScript and CSS assets.

In future we can add a service worker and menifest.json file to make this project a progressive web app which can run offline as a webapp.

### CODE REVIEW

**Comment by anthonyraymond** [comment]
:+1

**Comment by ziahamza** [comment]
This is awesome!!! ????
________________________________

**Comment by anthonyraymond** [comment]
@pratikborsadiya This PR should be closed in favor of #467 right?

**Comment by pratikborsadiya** [comment]
@anthonyraymond Yes let's close this in favour of #467.

**Pull request closed without merging**
