### PR TITLE
Add direct URL to files

### PR DESCRIPTION
**Pull request by SoreGums**
Ability to download files directly via pre-configured webserver. Simply
supply the base URL and links will be added to each file in the details
section.

### CODE REVIEW

**Comment by ziahamza** [comment]
hmm interesting. So its when you have a static server running along with aria2 and want to download files you have added in aria2. I like this idea. 

Do you also want to add some docs in the Readme for an example on how to setup DirectURL? I think others who use webui with aria2 will like this feature.

**Comment by SoreGums** [comment]
OK

I'll sort out a README entry later (about 12hrs from now - after work ;) ).

I'm using [send](https://github.com/pillarjs/send) with a simple index.js _(pretty much the exact one from readme)_ listening on local interface - doing everything through an ssh tunnel, was surprised that the SSH tunnel was able transfer at full dsl line speed _(15mbps in my case)_.

Since it is about the same number of steps going from nothing to nginx/apache or node.js/npm I'll just include the node.js info as I'm using it. using apache or nginx creates issues with regards to permissions and if the user already has nginx/apache they can sort that out themselves.

btw first time tinkering with AngularJS, took me a little while to figure what I was looking at :p
once I got a handle it was straight forward enough _(currently working on my first Ember project)_

**Comment by ziahamza** [comment]
Really nice that you are tinkering with AngularJS. Hope you will like Angular although its very similar to Ember after all. I have heard good things about Ember too.

I personally love NodeJS. Initially I wanted to add it as a build dependency, but then I just let things be simple.

**Comment by SoreGums** [comment]
done - it is pretty difficult to write this properly cause the scope is so huge...
if you were able to get aria2 running in daemon mode on a headless linux computer good chance you already know how to do this....

Don't feel like figuring out the Windows way cause I never run Windows servers for this sort of task ```run stuff in the cloud```

**Comment by ziahamza** [comment]
Have you tried looking into the node-static project? Basically, you can run a static server with npm and nodejs like so:

npm install -g node-static
cd /dir/to/arai2/downloads
static

**Comment by ziahamza** [comment]
For now, I will merge it in. Maybe I will update the send.js with static npm installed. thanks a lot for the documentation though, the rest  of it is really nice :)

**Comment by ziahamza** [comment]
Actually, also found this:
https://gist.github.com/willurd/5720255

which tells that you can create a simple http server with python 2 (which is pre installed on all linux boxes) like so:
python -m SimpleHTTPServer 8000

considering using that in the docs :)

**Comment by SoreGums** [comment]
yeah I couldn't find much looking for static http server that was easy.

1. cd to directory, run
2. support range queries

will check out the pyhton one ;)

**Comment by SoreGums** [comment]
[node-static](https://github.com/cloudhead/node-static) doesn't work properly can't handle [ in url (encoded)
[http-server](https://github.com/indexzero/http-server) uses a ridiculous amount of ram (80%) and goes slowly compared to send (4% - same file)

```python -m SimpleHTTPServer 8000``` works, too slow though can't handle range requests so speed goes up and down _(using fast download manager, multiple sections slams the connection and keeps it at peak speed with send)_ - though for the tutorial it might be enough

**Comment by ziahamza** [comment]
Hmmm ... I did not know. Thanks for letting me know the reasons behind the send package. Yeah, for now I have added the python as the default static server as its a one line install which most can follow, and if someone wants more then they can use the alternative packages :)

**Comment by SoreGums** [comment]
looks good - just a couple of tweaks to the details in #141

**Pull request merged**
