### PR TITLE
do not try default config if we have cookie

### PR DESCRIPTION
**Pull request by Twilight**
and fixed some wrong variable names

### CODE REVIEW

**Comment by ziahamza** [comment]
The variable name fixes were good catch ... thanks! :)
Perhaps for cookie config .. it should get higher priority then the default config, but I guess in case webui cannot connect then it should fallback to the default config. Otherwise users wont be able to change the config once cookie is assigned and it will always  disconnect. So perhaps append both into one array?

**Comment by Twilight** [comment]
there you go

**Comment by ziahamza** [comment]
Awesome! thanks @Twilight !! :)

**Comment by Twilight** [comment]
Welcome :)

**Pull request merged**
