### PR TITLE
multi-language support

### PR DESCRIPTION
**Pull request by mayf09**
Use angular-translate to support i18n and l10n, add  Simplified Chinese translation.

### CODE REVIEW

**Comment by ziahamza** [comment]
Looks good, thanks! It must have been a pain to refactor out most of the text. Do you also wanna add a button in the UI to allow users to switch languages directly?

**Comment by mayf09** [comment]
OK, I will add the button.

**Comment by ghostry** [comment]
php can automatically judge according to the client language settings display, I do not know whether the javascript can do it. I think automation is a very friendly way.

**Comment by ziahamza** [comment]
Javascript cant really access the http request used by browser to downlaod the webpage. Php can... so unfortunately we cant really make it fully automated without runing any server:
http://stackoverflow.com/questions/1043339/javascript-for-detecting-browser-language-preference

**Comment by ghostry** [comment]
A little regret, but also a good way to remember to select.

**Pull request merged**
