### PR TITLE
Added Dutch translation and unified related files

### PR DESCRIPTION
**Pull request by pepa65**
- Added full Dutch translation
- Translated more of the Thai interface
- Prepared rest of strings in index.html for translation
- Minor modifications and clean-up of the other translation files

### CODE REVIEW

**Comment by pepa65** [comment]
- This takes care of all the strings in index.html, but there are a number of messages/alerts in the RPC interface, and there is a huge amount of settings-related language in js/services/settings/settings.js
Eventually they should be tackled, but for daily users this takes care of the interface. Fortunately, the default English is used whenever a translation is missing.
- Is it a good idea to automate the enumeration of language files, so they don't have to be manually added to index.html and js/init.js for every new translation?
- Should there be an option in the configuration.js to explicitly set the language?

**Comment by pepa65** [comment]
I guess mayf09's pull takes care of the third point. :-)

**Comment by ziahamza** [comment]
Yeah, now there is a way to manually change the language from the bar. Maybe we can rememebr the user preference from cookies, and have an option for configuration.js for a default option!

**Comment by ziahamza** [comment]
Your changes look pretty good! do you already know thai and dutch at the same time? Its really incredble that you could translate it into both :D

**Comment by pepa65** [comment]
:-) My Dutch is way better than my Thai, but at least we have a start in a few very different scripts and languages. Then we can improve when someone with better language abilities comes along.

**Comment by ziahamza** [comment]
Well, every little helps. Thanks a ton for the push, as we already have 3 languages now to start from. Yeah, people can take it from here and it should be easy to add/update translations

**Comment by pepa65** [comment]
So what does "Closed" mean? That you're not going to merge it, or not yet?

**Comment by ziahamza** [comment]
ohh, I thought i merged it in local copy. but forgot to push. My bad.  Its merged now :)

**Comment by pepa65** [comment]
Oh OK! I looked at your repo to check something, and noticed that the index.html hadn't been updated -- until I saw that nothing had been..!

**Pull request merged**
