### PR TITLE
Add change language button.

### PR DESCRIPTION
**Pull request by mayf09**

### CODE REVIEW

**Comment by ziahamza** [comment]
I wasnt aware about flag-icon-css. the icons was a really good addition. I used it and it looks really nice! The whole translation feature now ties in really nicely :D

**Comment by pepa65** [comment]
Is this also inadvertently closed?

**Comment by ziahamza** [comment]
yeah, you are right. this was accidently closed too, will fix the merge conflicts

**Comment by ziahamza** [comment]
Merged and fixed the conflicts. The change finally lands in master :D Thank you so much for setting this up along with Chinese translations @mayf09. And really appreciate @pepa65 for pushing in Dutch and Thai support!

**Pull request merged**
