### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by jdarias**
Here´s the spanish translation :)
I noticed there are some strings that are not used, they are shown in english even though there´s a translated string available. I. e. "- To add a BitTorrent-Magnet URL, use the add URI option and add it there. " in the Add by torrent modal.

### CODE REVIEW

**Comment by ziahamza** [comment]
I have fixed the ```- To add a BitTorrent-Magnet URL, use the add URI option and add it there. ``` translate bug. Let me know if you find more! @jdarias

**Comment by ziahamza** [comment]
Also, this looks good. You did it!! :)

**Comment by jdarias** [comment]
Great! 
Indeed i found several of those, i´ll make a list and post them here.

**Comment by jdarias** [comment]
In connection settings modal:
_(Requires an appropriate webserver to be configured.) _

In the about modal:
_Or you can open the latest version in browser through:_

Under the Manage menu:
_Shutdown server_

Here are ones in a screenshot:
[Imgur](http://i.imgur.com/KZqTVq5.png?1)
http://imgur.com/KZqTVq5

**Comment by ziahamza** [comment]
Thanks @jdarias for compiling the list of errors! I have fixed most of them and they are pushed to master. The only one I did not is ```Shutdown server``` as most translation except English translation define this. Have you defined it in the Spanish translation?

**Comment by jdarias** [comment]
No, I haven´t, 
I am adding a new line with this in es_ES.js.
`    'Shutdown Server': 'Desactivar servidor',`

**Pull request merged**
