### PR TITLE
Finalizing language integration

### PR DESCRIPTION
**Pull request by pepa65**
Thai and Dutch now with the program.
(What is the use of the en_US.js file? It's not complete, but its presence doesn't seem to make a difference. Unless it is preparing for a refactoring.)

### CODE REVIEW

**Comment by ziahamza** [comment]
You are right about the US file..., unless we refactor we don't need it. So
maybe also delete it in your branch and update the pull request and I will
merge it in together :)

**Comment by pepa65** [comment]
Something changed and the en_US.js is now mandatory. I updated it to include all strings from the template.

**Comment by ziahamza** [comment]
Merged it in with the refactor :)

**Comment by pepa65** [comment]
The problem with the current situation is, that the missing strings in Thai and Chinese no longer give the English, so it's just empty... Can we change this?? That way we can just gradually translate interfaces without having to demand full translations.
The other option is to 'manually' supply all English strings in every translation file, but that feels wrong...

**Comment by ziahamza** [comment]
Just pushed in a change, to automatically merge english translation in case anything is missing. The master should now have the change :)

**Comment by pepa65** [comment]
Can you also automatically include all the language files in js/tranlations ?? Then future inclusions don't need to modify js/init.js and index.html

**Pull request merged**
