### PR TITLE
Adjust css style

### PR DESCRIPTION
**Pull request by kuoruan**

### CODE REVIEW

**Comment by ziahamza** [comment]
💯 👍

**Comment by vBm** [comment]
Just noticed that this merge "broke" perfect usecase for me :D 
Was using `stats` set to `false` so i could avoid having speed graph visible which was heavy on the cpu and still see the total speeds <3

local revert of https://github.com/ziahamza/webui-aria2/commit/8e84b9608112f94f8ccb4af2142059517ec02a3c#diff-eacf331f0ffc35d4b482f1d15a887d3bR333 change

**Comment by ziahamza** [comment]
ohhh, @vBm , that makes sense. the graph can be intense on CPU. so you have your local copy, before the changes from this PR?

**Comment by vBm** [comment]
@ziahamza no, I've just applied another change on top of it which removes moving those two `span`'s to `li`.

**Pull request merged**
